import Head from 'next/head'
import Image from 'next/image'

import BackgoundIllustration from '../components/BackgoundIllustration'
import Topview from '../components/Topview'
import Price from '../components/Price'
import Sample from '../components/Sample'
import WhatIs from '../components/WhatIs'
import Workflow from '../components/Workflow'
import Message2 from '../components/Message2'
import Question from '../components/Question'
import Quickstart from '../components/Quickstart'
import Apply from '../components/Apply'
import Footer from '../components/Footer'
import Contact from '../components/Contact'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >

        <BackgoundIllustration>
          <Topview />
          <Price />
          <Sample />
          <WhatIs />
          <Workflow />
          <Message2 />
          <Question />
          <Quickstart />
          {/* <Apply /> */}
          <Contact />
          <Footer />

        </BackgoundIllustration>
      </main>


    </div>
  )
}
